name: learn_riverpod2
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  build_runner: ^2.4.15
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_gherkin: ^2.0.0
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod_test: ^0.1.9
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
